[QP.woMCA]
"Boxer-IrishMan-Gladiator" = [37, 41, 45, 49]
"chess" = [37, 41, 45, 49]
"ChessPieces" = [33, 40, 45, 49]
"NagoyaDataLeading" = [38, 43, 49, 51]
"NagoyaFujita" = [36, 40, 45, 49]
"NagoyaOrigami" = [34, 39, 44, 49]
"Tunnel_Train" = [35, 40, 45, 49]
"Boys" = [37, 41, 45, 49]

[QP.wMCA]
"Boxer-IrishMan-Gladiator" = [33, 37, 41, 45]
"chess" = [34, 37, 41, 45]
"ChessPieces" = [30, 36, 40, 45]
"NagoyaDataLeading" = [33, 38, 44, 47]
"NagoyaFujita" = [32, 36, 42, 46]
"NagoyaOrigami" = [31, 36, 40, 45]
"Tunnel_Train" = [30, 35, 40, 45]
"Boys" = [34, 37, 41, 45]

[default_pattern]
"py" = "frame#{:03d}.png"
"c" = "frame#%03d.png"

[pattern]
"Boxer-IrishMan-Gladiator" = "frame_{:03d}.png"
"chess" = "frame_{:03d}.png"
"ChessPieces" = "frame_{:03d}.png"
"NagoyaDataLeading" = "NagoyaDataLeading_f{:04d}.png"
"NagoyaFujita" = "NagoyaFujita_f{:04d}.png"
"Tunnel_Train" = "Tunnel_Train_2c_f{:04d}.png"
"Boys" = "Image{:03d}.bmp"
"Cars" = "Image{}.bmp"
"Experimenting" = "Image{:03d}.bmp"
"Matryoshka" = "Image{}.bmp"

[start_idx]
"Boxer-IrishMan-Gladiator" = 0
"chess" = 0
"ChessPieces" = 0
"NagoyaDataLeading" = 1
"NagoyaFujita" = 1
"Tunnel_Train" = 0
"Boys" = 0
"Cars" = 21
"Experimenting" = 0
"Matryoshka" = 0
