frames = 30

[cases]
vtm_types = ["AI", "RA"]
seqs = [
    "Boys",
    "Cars",
    "Experimenting",
    "Matryoshka",
]

[path]
dataset = "D:/Dataset/MPEG"

[app]
ffmpeg = "C:/Program Files/ffmpeg/bin/ffmpeg.exe"
encoder = "D:/MPEG/MPEG144/code/VVCSoftware_VTM/bin/ninja/msvc-19.37/x86_64/release/EncoderApp.exe"
preproc = "D:/MPEG/MPEG143/code/MCA/cmake-build-release/src/bin/mca-preproc.exe"
postproc = "D:/MPEG/MPEG143/code/MCA/cmake-build-release/src/bin/mca-postproc.exe"
rlc = "D:/MPEG/MPEG146/code/rlc/Program/cmake-build-release/RLC30.exe"
