frames = 30

[cases]
vtm_types = ["AI", "RA"]
seqs = [
    "Boys",
    "Cars",
    "Experimenting",
    "Matryoshka",
]

[path]
dataset = "D:/Dataset/MPEG"

[app]
ffmpeg = "E:/Program Files/ffmpeg/bin/ffmpeg.exe"
encoder = "D:/MPEG/MPEG144/code/VVCSoftware_VTM/bin/ninja/msvc-19.37/x86_64/release/EncoderApp.exe"
preproc = "D:/MPEG/MPEG143/code/libMCA/cmake-build-release-visual-studio/apps/main_preproc.exe"
postproc = "D:/MPEG/MPEG143/code/libMCA/cmake-build-release-visual-studio/apps/main_postproc.exe"
rlc = "E:/Code/MPEG/MPEG146/rlc/Program/cmake-build-release/RLC30.exe"
