dataset_root = "E:/Code/SIGS/230818_VVC/dataset/videos"
ffmpeg = "C:/Program Files/ffmpeg/bin/ffmpeg.exe"

[raw2png]
param_file = "./rlc.cfg.bak"
src_file = "./source.yuv"
dst_dir = "./imgs/raw2png"

[preprocess]
program = "E:/Code/SIGS/230508_LVC/code/libLVC/cmake-build-release-visual-studio/apps/main_preprocess.exe"
param_file = "./rlc.cfg.bak"
calibration_file = "./calibration.xml"
src_dir = "./imgs/raw2png"
dst_dir = "./imgs/preprocessed"

[pre2yuv]
param_file = "./rlc.cfg.bak"
src_dir = "./imgs/preprocessed"
dst_file = "./imgs/pre2yuv.yuv"

[codec]
program = "E:/Code/SIGS/230818_VVC/code/VVCSoftware_VTM/bin/ninja/msvc-19.37/x86_64/release/EncoderApp.exe"
encode_mode_cfg_file = "E:/Code/SIGS/230818_VVC/code/VVCSoftware_VTM/cfg/encoder_intra_vtm.cfg"
param_file = "./vtm.cfg.bak"
size_ref_img_file = "./imgs/preprocessed/001.png"
src_file = "./imgs/pre2yuv.yuv"
dst_file_fstr = "./imgs/encoded/{qp}.bin"
log_file_fstr = "./imgs/encoded/{qp}.log"
recon_file_fstr = "./imgs/decoded/{qp}.yuv"

[codec.ctcqp]
Boxer-IrishMan-Gladiator = [37, 41, 45, 49]
chess = [37, 41, 45, 49]
ChessPieces = [33, 40, 45, 49]
NagoyaDataLeading = [38, 43, 49, 51]
NagoyaFujita = [36, 40, 45, 49]
NagoyaOrigami = [36, 40, 45, 49]
Tunnel_Train = [35, 40, 45, 49]

[dec2png]
size_ref_img_file = "./imgs/preprocessed/001.png"
src_file_pattern = "./imgs/decoded/*.yuv"
dst_dir_fstr = "./imgs/dec2png/{stem}"

[postprocess]
program = "E:/Code/SIGS/230508_LVC/code/libLVC/cmake-build-release-visual-studio/apps/main_postprocess.exe"
param_file = "./rlc.cfg.bak"
calibration_file = "./calibration.xml"
src_dirs = "./imgs/dec2png"
dst_dir_fstr = "./imgs/postprocessed/{qp}"

[render]
program = "E:/Code/SIGS/230508_LVC/code/rlc-master/cmake-build-release-visual-studio/apps/RLC.exe"
param_file = "./rlc.cfg.bak"
calibration_file = "./calibration.xml"
src_dirs = "./imgs/postprocessed"
dst_dir_fstr = "./imgs/rendered/{qp}"

[baseline_render]
program = "E:/Code/SIGS/230508_LVC/code/rlc-master/cmake-build-release-visual-studio/apps/RLC.exe"
param_file = "./rlc.cfg.bak"
calibration_file = "./calibration.xml"
src_dir = "./imgs/raw2png"
dst_dir = "./imgs/rendered_base"

[computation]
base_dir = "./imgs/rendered_base"
render_dirs = "./imgs/rendered"
render_ref_dirs = "./imgs/rendered_ref"
log_file_fstr = "./imgs/encoded/{qp}.log"
ref_log_file_fstr = "./imgs/encoded_ref/{qp}.log"
