root = "E:/Code/SIGS/230818_VVC/dataset"

[program]
ffmpeg = "C:/Program Files/ffmpeg/bin/ffmpeg.exe"
encoder = "E:/Code/SIGS/230818_VVC/code/VVCSoftware_VTM/bin/ninja/msvc-19.37/x86_64/release/EncoderApp.exe"
preprocess = "E:/Code/SIGS/230508_LVC/code/libLVC/cmake-build-release-visual-studio/apps/main_preprocess.exe"
postprocess = "E:/Code/SIGS/230508_LVC/code/libLVC/cmake-build-release-visual-studio/apps/main_postprocess.exe"
rlc = "E:/Code/SIGS/230508_LVC/code/rlc-master/cmake-build-release-visual-studio/apps/RLC.exe"

[base.raw2png]
rlc_cfg = "./config/{seq_name}/rlc.cfg"
dst = "./playground/base/raw2png"

[base.render]
rlc_cfg = "./config/{seq_name}/rlc.cfg"
dst = "./playground/base/render"

[wopre.raw2yuv]
src = "./image"
dst = "./playground/wopre/raw2yuv"

[wopre.codec]
vtm_cfg = "./config/{seq_name}/vtm.cfg"
dst = "./playground/wopre/codec"

[wopre.dec2png]
rlc_cfg = "./config/{seq_name}/rlc.cfg"
dst = "./playground/wopre/dec2png"

[wopre.render]
rlc_cfg = "./config/{seq_name}/rlc.cfg"
dst = "./playground/wopre/render"

[pre.preprocess]
rlc_cfg = "./config/{seq_name}/rlc.cfg"
src = "./image"
dst = "./playground/pre/preprocess"

[pre.pre2yuv]
rlc_cfg = "./config/{seq_name}/rlc.cfg"
dst = "./playground/pre/pre2yuv"

[pre.codec]
vtm_cfg = "./config/{seq_name}/vtm.cfg"
dst = "./playground/pre/codec"

[pre.dec2png]
rlc_cfg = "./config/{seq_name}/rlc.cfg"
dst = "./playground/pre/dec2png"

[pre.postprocess]
rlc_cfg = "./config/{seq_name}/rlc.cfg"
dst = "./playground/pre/postprocess"

[pre.render]
rlc_cfg = "./config/{seq_name}/rlc.cfg"
dst = "./playground/pre/render"

[common.compose]
dst = "./playground/common/compose"

[common.compute]
dst = "./playground/common/compute"
