[project]
name = "VVC-Scripts"
version = "0.0.0"
description = ""
authors = [{ name = "Starry-OvO", email = "starry.qvq@gmail.com" }]
dependencies = ['opencv-contrib-python']
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }

[tool.pdm.dev-dependencies]
lint = ["ruff", "black"]

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ["py38", "py39", "py310", "py311"]

[tool.ruff]
line-length = 120
select = ["W", "E", "F", "I"]
ignore = ["E402", "E501"]
target-version = "py38"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
