[project]
name = "lvccc"
version = "0.5.0"
description = ""
authors = [{ name = "Zhuo Tan", email = "tz23@mails.tsinghua.edu.cn" }]
dependencies = ["pydantic", "scipy", "opencv-python", "matplotlib", 'xxhash']
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["lvccc"]

[tool.rye]
managed = true
dev-dependencies = ["pytest"]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
select = ["W", "E", "F", "I", "UP", "YTT", "A", "B", "C4", "PIE", "PT", "PERF", "FURB"]
ignore = ["E402", "E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
