[project]
name = "MCA-Benchmark"
version = "0.1.0"
description = ""
authors = [{ name = "Starry-OvO", email = "starry.qvq@gmail.com" }]
dependencies = ["pydantic", "scipy", "opencv-contrib-python", "matplotlib"]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = { text = "MIT" }

[tool.rye]
managed = true
virtual = true

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
select = ["W", "E", "F", "I", "UP", "YTT", "A", "B", "C4", "PIE", "PT", "PERF", "FURB"]
ignore = ["E402", "E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
