frames = 300

default_pattern = "frame#%03d.png"

[cases]
vtm_types = ["AI", "RA"]
seqs = []

[path]
input = ""
output = ""

[app]
ffmpeg = "ffmpeg"
encoder = "EncoderApp"
preproc = "mca-preproc"
postproc = "mca-postproc"
rlc = "RLC40"

[QP.anchor]
"NagoyaFujita" = []
"NagoyaOrigami" = []
"TempleBoatGiantR32" = []
"Boys" = []
"Experimenting" = []
"Motherboard" = []
"MiniGarden" = []

[QP.wMCA]
"NagoyaFujita" = []
"NagoyaOrigami" = []
"TempleBoatGiantR32" = []
"Boys" = []
"Experimenting" = []
"Motherboard" = []
"MiniGarden" = []

[pipeline]
"NagoyaFujita" = 0
"NagoyaOrigami" = 0
"TempleBoatGiantR32" = 1
"Boys" = 1
"Experimenting" = 1
"Motherboard" = 1
"MiniGarden" = 1
