frames = 300

default_pattern = "frame#%03d.png"

[cases]
vtm_types = ["AI", "RA"]
seqs = []

[path]
input = ""
output = ""

[path.pattern]
"ComplexObjectMove" = "ComplexObjectMove/frame_%03d.png"
"UnicornLinearCam" = "UnicornLinearCam/frame_%03d.png"
"NagoyaDataLeading" = "NagoyaDataLeading/NagoyaDataLeading_f%04d.png"
"NagoyaFujita" = "NagoyaFujita/NagoyaFujita_f%04d.png"
"NagoyaOrigami" = "NagoyaOrigami/NagoyaOrigami_f%04d.png"
"Tunnel_Train" = "Tunnel_Train/Tunnel_Train_2c_f%04d.png"
"Boys" = "Boys/Image%03d.bmp"
"Cars" = "Cars/Image%d.bmp"
"Experimenting" = "Experimenting/Image%03d.bmp"
"Matryoshka" = "Matryoshka/Image%d.bmp"
"Tri-viewpoint" = "Tri-viewpoint/frame%03d.png"
"Motherboard" = "Motherboard/img_%03d.bmp"

[app]
ffmpeg = "ffmpeg"
encoder = "EncoderApp"
preproc = "mca-preproc"
postproc = "mca-postproc"
rlc = "RLC30"

[QP.woMCA]
"NagoyaDataLeading" = []
"NagoyaFujita" = []
"NagoyaOrigami" = []
"Tunnel_Train" = []
"Boys" = []
"Cars" = []
"Experimenting" = []
"Matryoshka" = []
"Motherboard" = []

[QP.wMCA]
"NagoyaDataLeading" = []
"NagoyaFujita" = []
"NagoyaOrigami" = []
"Tunnel_Train" = []
"Boys" = []
"Cars" = []
"Experimenting" = []
"Matryoshka" = []
"Motherboard" = []

[start_idx]
"ComplexObjectMove" = 0
"UnicornLinearCam" = 0
"NagoyaDataLeading" = 1
"NagoyaFujita" = 1
"NagoyaOrigami" = 1
"Tunnel_Train" = 0
"Boys" = 0
"Cars" = 21
"Experimenting" = 0
"Tri-viewpoint" = 0
"Matryoshka" = 0
"Motherboard" = 0
